### ISSUE TITLE
if reiceive choice is set, but the screen rotates, the choice menu is shown again

### ISSUE THREAD

**Issue by tbocek** [coinblesk/coinblesk-client-gui#19]

**Comment by albrechta** [comment]
View should be wrapped in DialogFragment, but it requires additional refactoring of the nfc/wifi/BT communication servers and clients (they should outlive the view).

**Comment by albrechta** [comment]
Uncoupling the communication completely from the GUI is not possible because the Android NFC API  requires an activity.
However, rotation is now disabled during receive/accept to prevent losing the connection.
