### ISSUE TITLE
Wallet service is started multiple times

### ISSUE THREAD

**Issue by albrechta** [coinblesk/coinblesk-client-gui#41]
The wallet service may be started multiple times (i.e. multiple peer groups, etc. are running simultaneously).

**Comment by albrechta** [comment]
To reproduce this behavior: switch between portrait and landscape mode a few times. 
Switching creates a new activity, which loads the wallet again (`onStartCommand` is called, also watch the PeerGroup threads in the debug view). 

`stopService()` is commented in the `MainActivity.onDestroy()`. Maybe this would solve this issue? Would still load the wallet again, but shut down the old one. 
Alternatively, the wallet could be loaded in `Service.onCreated` instead of `onStartCommand`?

**Comment by dcale** [comment]
closed with latest commit
