### ISSUE TITLE
Fiat currency symbol always USD

### ISSUE THREAD

**Issue by albrechta** [coinblesk/coinblesk-client-gui#42]
The conversion to fiat does not work properly, displayed symbol is always USD even though, for instance, EUR is set.

**Comment by dcale** [comment]
is this still the case with the lastest master? Exchange rates are not changed/fetched immediately, it will take some time untill you have the right exchange rate

**Comment by albrechta** [comment]
Ah yes, it changes if I switch between the tabs. After a fresh install, it displays CHF but in the settings, the default seems to be EUR. If I navigate back to the main activity, the symbol is updated. It is probably just the initial sync.

**Comment by dcale** [comment]
can we close this?
