### ISSUE TITLE
High Energy Consumption

### ISSUE THREAD

**Issue by tbocek** [coinblesk/coinblesk-client-gui#53]
![image-808a71ef85fd1bc5e98a85e94ece5aceb512a74419eda262169917605980e53e-v](https://cloud.githubusercontent.com/assets/1283564/14232566/bff79cb2-f9ae-11e5-99a3-460be3ecea01.jpg)

Coinblesk uses a lot of battery, I guess that all the communication channels are always up. (reparted by Andri)

**Comment by dcale** [comment]
This is fixed with the new commit
