### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by tbocek** [coinblesk/coinblesk-client-gui#81]
ception: Attempt to invoke virtual method 'java.lang.String org.bitcoinj.core.NetworkParameters.getId()' on a null object reference
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at android.app.ActivityThread.-wrap4(ActivityThread.java)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.bitcoinj.core.NetworkParameters.getId()' on a null object reference
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at com.coinblesk.payments.WalletService.onCreate(WalletService.java:160)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
07-07 15:44:12.940 26936 26936 E AndroidRuntime: 	... 8 more

**Comment by albrechta** [comment]
Fixed, network parameters are initialized in onCreate of the application instead of the main activity.
