### ISSUE TITLE
Not working with Android 7

### ISSUE THREAD

**Issue by tbocek** [coinblesk/coinblesk-client-gui#92]
FATAL EXCEPTION: main
09-06 11:36:08.442  5302  5302 E AndroidRuntime: Process: com.coinblesk.client, PID: 5302
09-06 11:36:08.442  5302  5302 E AndroidRuntime: android.view.InflateException: Binary XML file line #7: Binary XML file line #10: Error inflating class ImageView
09-06 11:36:08.442  5302  5302 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class ImageView
09-06 11:36:08.442  5302  5302 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.coinblesk.client:drawable/nfc with resource ID #0x7f0200ae
09-06 11:36:08.442  5302  5302 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/nfc.xml from drawable resource ID #0x7f0200ae
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:854)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:157)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:145)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:57)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:53)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:980)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1039)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at com.coinblesk.client.KeyboardFragment.onCreateView(KeyboardFragment.java:89)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at com.coinblesk.client.SendPaymentFragment.onCreateView(SendPaymentFragment.java:59)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.app.Fragment.performCreateView(Fragment.java:2352)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:815)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:563)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v13.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:911)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 11:36:08.442  5302  5302 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1075)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1358)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:619)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Path string cannot be empty.
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.util.PathParser.nCreatePathDataFromString(Native Method)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.util.PathParser.-wrap1(PathParser.java)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.util.PathParser$PathData.<init>(PathParser.java:74)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1556)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1507)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable.inflateChildElements(VectorDrawable.java:693)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:598)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1224)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1197)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
09-06 11:36:08.443  5302  5302 E AndroidRuntime: 	... 82 more

**Comment by christiankiller** [comment]
🌚 wtf

**Comment by tbocek** [comment]
nfc.xml was broken with API version 7, fixed now
